name: laksadart
description: Dart library for Zilliqa's Blockchain, including Schnorr, wallet/account/keys manager, RPCMethod, Transactions and Contracts deploy/call.
version: 0.2.0
homepage: "https://github.com/firestack-lab/laksaDart"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bip32: ^2.0.0
  bip39: ^1.0.6
  bech32: ^0.2.0
  collection: ^1.15.0
  convert: ^3.0.0
  crypto: ^3.0.1
  fixnum: ^1.0.0
  http: ^0.13.3
  meta: ^1.4.0
  pointycastle: ^3.0.1
  protobuf: ^2.0.0
  tuple: ^2.0.0
  uuid: ^3.0.4
  validators: ^3.0.0
  freezed_annotation: ^0.14.2
  source_helper: ^1.2.1
  analyzer: ^2.0.1

dev_dependencies:
  build_runner: ^2.0.4
  json_serializable: ^5.0.0
  freezed: ^0.14.2
  test: ^1.17.5
